### ISSUE TITLE
Valores que devem ser extraído no FRONT_TAG_PATH_REGEXES e BRANCH_REGEXES

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/clea#1]
Em conversa com o Gustavo visualizamos novos campos que devem ser extraído no FRONT_TAG_PATH_REGEXES e BRANCH_REGEXES.

Segue a lista de campos: 
 
* title  = XML (front->article-meta->title-group->article-title)
* translated_titles = XML (front->article-meta->title-group->article-title@xml:lang) 
* section = XML (article-meta->article-categories->subj-group->@sub-group-type="heading"->subject)
* authors = XML (front->article-meta->contrib-group->contrib->name->surname && given-name)
* abstract = XML (front->article-meta->abstract)
* abstracts = XML (front->sub-article->abstract)
* doi = XML (front->article-meta->article-id@doi)
* pid = XML (front->article-meta->article-id@publisher-id)
* languages = XML(sub-article@xml:lang)
* abstract_languages = XML (sub-article->abstract@xml:lang)
* original_language = XML (article@xml:lang)
* publication_date = XML (front->article-meta->pub-date@epub-ppub)
* keywords = XML (article-meta->kwd-group->kwd)
* elocation = XML (front->article-meta->elocation)
* fpage = XML (front->article-meta->fpage)
* fpage_sequence = XML (front->article-meta->fpage@seq)
* lpage = XML (front->article-meta->lpage)

**Comment by danilobellini** [comment]
Clea v0.2.0 is out. It's a massive update, including a new documentation in its README. I think every requested attribute/element (even the `<sub-article>` stuff) is available in this new version. Some fields were ambiguous, so I tried to put everything I found regarding them. I've just published Clea v0.2.0 in PyPI. It's not exhaustively tested yet. If there's anything missing (or failing), please let me know.

**Comment by jamilatta** [comment]
Hi @danilobellini 

Using the new version Clea v0.2.0 the **clea.join:aff_contrib_inner_join**, return a ValueError: too many values to unpack! 

See:

<img width="1260" alt="Screenshot 2019-04-08 10 58 39" src="https://user-images.githubusercontent.com/373745/55730054-be84b480-59ed-11e9-9d9d-a9768d27c2b3.png">

Let me know if I need to use another function of join.py module. 

Look where I using the mentioned function on document-store: 

<img width="981" alt="Screenshot 2019-04-08 11 04 51" src="https://user-images.githubusercontent.com/373745/55730270-2d620d80-59ee-11e9-8589-c5aa43f68ceb.png">

**Comment by danilobellini** [comment]
How about the `aff_contrib_inner` and `aff_contrib_full` functions? See the example in the `README.md` file, it tells how to get all information (you might miss data if you use the legacy `aff_contrib_inner_join`).

**Comment by jamilatta** [comment]
Very good man. 

Now I am using aff_contrib_inner and it is working.

Thanks.

**Comment by danilobellini** [comment]
The `aff_contrib_inner_join` legacy function is fixed in v0.2.1, which have just been released.
