### ISSUE TITLE
Comportamento inesperado para a tag: trans-abstract.

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/clea#2]
Ao realizarmos o processamento de documentos antigos....., verificarmos um comportamento inesperado no endpoint **/front** do Kernel, que está utilizando o Clea v0.2.2, segue um exemplo:

[example.xml.zip](https://github.com/scieloorg/clea/files/3137929/example.xml.zip)

Repare que esse XML tem apenas uma tag **trans-abstract** 

Como resultado do Clea retorna o seguinte JSON: 

<img width="1679" alt="Screenshot 2019-05-02 09 28 52" src="https://user-images.githubusercontent.com/373745/57075271-b81bec80-6cbc-11e9-9f8f-de160ea26d82.png">

Portanto o Clea produz um item a mais sem o atributo "lang".

**Comment by danilobellini** [comment]
Fixed in Clea v0.3.0
