### ISSUE TITLE
Considerar os atributos e seus valores para retornar na estrutura de dicionários

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/clea#4]
Temos o seguinte caso:

Todos os documentos deverão receber o novo PID, que no XML do documento será representado no elemento /article/front/article-meta/article-id[@pub-id-type = "publisher-id" and @specific-use="scielo-v3"].

A representação do PID padrão S0001-37652000000100002 passa a ser: /article/front/article-meta/article-id[@pub-id-type = "publisher-id" and @specific-use="scielo-v2"].

A representação do PID anterior ao padrão S0001-37652000000100002 passa a ser: /article/front/article-meta/article-id[@pub-id-type = "publisher-id" and @specific-use="scielo-v1"].

Ou seja, no XML teríamos:

```xml
<article-id pub-id-type="publisher-id" specific-use="scielo-v2">S0103-90161998000100024</article-id>
<article-id pub-id-type="publisher-id" specific-use="scielo-v1">S0103-9016(98)05500124</article-id>
<article-id pub-id-type="publisher-id" specific-use="scielo-v3">xUAFAEMAO12A403jXumqkadeadka</article-id>
```

Atualmente quando recuperamos o que corresponde article-id, chega uma lista de valores. E isso é incompleto, pois não deveríamos nos basear na ordem dos itens da lista. O ideal é que cada item fosse caracterizado com os atributos.

**Comment by danilobellini** [comment]
Qual o melhor nome para os campos?

* `article_meta.pid1`
* `article_meta.pid_v1`
* `article_meta.scielo_v1`
* `article_meta.article_pid_v1`

Algo diferente...

Ah, o leitor vai pegar só o `specific-use`, e vai funcionar com typos e outras falhas (sem hífen, valores como `specifise="scielo1"`, etc.). Se o `specific-use` for usado em outro contexto dentro dessa mesma tag `<article-id>`, esta biblioteca terá de ser adaptada.

**Comment by joffilyfe** [comment]
✅  `article_meta.article_pid_v1`!

**Comment by gustavofonseca** [comment]
> ✅ `article_meta.article_pid_v1`!

É redundante usar `article` dentro do contexto do `article_meta`, pois tecnicamente todos os atributos neste contexto se referem ao `article`. Eu sugiro algo como `article_meta.scielo_pid_v1`, pensando que no futuro poderão surgir mais metadados específicos de scielo dentro do articlemeta.

**Comment by danilobellini** [comment]
Novos `scielo_pid_v1`, `scielo_pid_v2` e `scielo_pid_v3` disponíveis na v0.4.1.
